require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe HistoriesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # History. As you add validations to History, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    build(:history).attributes
  }

  let(:invalid_attributes) {
    build(:invalid_history).attributes
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HistoriesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all histories as @histories" do
      history = History.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:histories)).to eq([history])
    end
  end

  describe "GET #show" do
    it "assigns the requested history as @history" do
      history = History.create! valid_attributes
      get :show, params: {id: history.to_param}, session: valid_session
      expect(assigns(:history)).to eq(history)
    end
  end

  describe "GET #new" do
    it "assigns a new history as @history" do
      get :new, params: {}, session: valid_session
      expect(assigns(:history)).to be_a_new(History)
    end
  end

  describe "GET #edit" do
    it "assigns the requested history as @history" do
      history = History.create! valid_attributes
      get :edit, params: {id: history.to_param}, session: valid_session
      expect(assigns(:history)).to eq(history)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new History" do
        expect {
          post :create, params: {history: valid_attributes}, session: valid_session
        }.to change(History, :count).by(1)
      end

      it "assigns a newly created history as @history" do
        post :create, params: {history: valid_attributes}, session: valid_session
        expect(assigns(:history)).to be_a(History)
        expect(assigns(:history)).to be_persisted
      end

      it "redirects to the created history" do
        post :create, params: {history: valid_attributes}, session: valid_session
        expect(response).to redirect_to(History.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved history as @history" do
        post :create, params: {history: invalid_attributes}, session: valid_session
        expect(assigns(:history)).to be_a_new(History)
      end

      it "re-renders the 'new' template" do
        post :create, params: {history: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        build(:update_history).attributes
      }

      it "updates the requested history" do
        history = History.create! valid_attributes
        put :update, params: {id: history.to_param, history: new_attributes}, session: valid_session
        history.reload
        expect(controller.notice).to eq("History was successfully updated.")
      end

      it "assigns the requested history as @history" do
        history = History.create! valid_attributes
        put :update, params: {id: history.to_param, history: valid_attributes}, session: valid_session
        expect(assigns(:history)).to eq(history)
      end

      it "redirects to the history" do
        history = History.create! valid_attributes
        put :update, params: {id: history.to_param, history: valid_attributes}, session: valid_session
        expect(response).to redirect_to(history)
      end
    end

    context "with invalid params" do
      it "assigns the history as @history" do
        history = History.create! valid_attributes
        put :update, params: {id: history.to_param, history: invalid_attributes}, session: valid_session
        expect(assigns(:history)).to eq(history)
      end

      it "re-renders the 'edit' template" do
        history = History.create! valid_attributes
        put :update, params: {id: history.to_param, history: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested history" do
      history = History.create! valid_attributes
      expect {
        delete :destroy, params: {id: history.to_param}, session: valid_session
      }.to change(History, :count).by(-1)
    end

    it "redirects to the histories list" do
      history = History.create! valid_attributes
      delete :destroy, params: {id: history.to_param}, session: valid_session
      expect(response).to redirect_to(histories_url)
    end
  end

  describe "POST #import" do
    let(:import_file) {
      fixture_file_upload('spec/fixtures/csv/history.csv', 'text/comma-separated-values')
    }

    let(:mismatch_import_file) {
      fixture_file_upload('spec/fixtures/csv/history_mismatch.csv', 'text/comma-separated-values')
    }

    before :each do
      csv = fixture_file_upload('spec/fixtures/csv/use.csv', 'text/comma-separated-values')
      Use.csv_file_import(csv)
      csv = fixture_file_upload('spec/fixtures/csv/account.csv', 'text/comma-separated-values')
      Account.csv_file_import(csv)
    end

    context "with valid import data" do
      it "csv file upload" do
        expect {
          post :import, params: {file: import_file}, session: valid_session
        }.to change(History, :count).by(6)
        expect(response).to redirect_to(histories_url)
        expect(controller.notice).to eq("History was successfully imports.")
      end
    end

    context "with invalid import data" do
      it "not upload file" do
        expect {
          post :import, params: {file: nil}, session: valid_session
        }.to change(History, :count).by(0)
        expect(response).to redirect_to(histories_url)
        expect(controller.alert).to eq("History was unsuccessfully imports.<br/>Please choose the file to be import.")
      end

      it "import format mismatch" do
        expect {
          post :import, params: {file: mismatch_import_file}, session: valid_session
        }.to change(History, :count).by(0)
        expect(response).to redirect_to(histories_url)
        expect(controller.alert).to eq("History was unsuccessfully imports.<br/>The file format is different.")
      end
    end
  end

end
